const info = (function(){
  //first one is empty so the pokedex numbers line up with array numbers
  let names = ['', 'Bulbasaur', 'Ivysaur', 'Venusaur', 'Charmander', 'Charmeleon', 'Charizard', 'Squirtle', 'Wartortle', 'Blastoise',
    'Caterpie', 'Metapod', 'Butterfree', 'Weedle', 'Kakuna', 'Beedrill', 'Pidgey', 'Pidgeotto', 'Pidgeot', 'Rattata', 'Raticate',
    'Spearow', 'Fearow', 'Ekans', 'Arbok', 'Pikachu', 'Raichu', 'Sandshrew', 'Sandslash', 'Nidoran(Female)', 'Nidorina', 'Nidoqueen',
    'Nidoran(male)', 'Nidorino', 'Nidoking', 'Celfairy', 'Clefable', 'Vulpix', 'Ninetails', 'Jigglypuff', 'Wigglytuff', 'Zubat', 'Golbat',
    'Oddish', 'Gloom', 'Vileplume', 'Paras', 'Parasect', 'Venonat', 'Venomoth', 'Diglett', 'Dugtrio', 'Meowth', 'Persian', 'Psyduck',
    'Golduck', 'Mankey', 'Primeape', 'Growlithe', 'Arcanine', 'Poliwag', 'Poliwhirl', 'Poliwrath', 'Abra', 'Kadabra', 'Alakazam', 'Machop',
    'Machoke', 'Machamp', 'Bellsprout', 'Weepinbell', 'Victreebel', 'Tentacool', 'Tentacruel', 'Geodude', 'Gravler', 'Golem', 'Ponyta',
    'Rapidash', 'Slowpoke', 'Slowbro', 'Magnemite', 'Magneton', `Farfetch'd`, 'Doduo', 'Dodrio', 'Seel', 'Dewgong', 'Grimer', 'Muk',
    'Shellder', 'Cloyster', 'Gastly', 'Haunter', 'Gengar', 'Onix', 'Drowzee', 'Hypno', 'Krabby', 'Kingler', 'Voltorb', 'Electrode',
    'Exeggcute', 'Exeggutor', 'Cubone', 'Marowak', 'Hitmonlee', 'Hitmonchan', 'Likitung', 'Koffing', 'Weexing', 'Rhyhorn', 'Rhydon',
    'Chansey', 'Tengela', 'Kabgaskhan', 'Horsea', 'Seadra', 'Goldeen', 'Seaking', 'Staryu', 'Starmie', 'Mr. Mime', 'Scyther', 'Jynx',
    'Electabuzz', 'Magmar', 'Pinsir', 'Taurus', 'Magikarp', 'Garados', 'Lapras', 'Ditto', 'Eevee', 'Vaporeon', 'Jolteon', 'Flareon',
    'Porygon', 'Omanyte', 'Omastar', 'Kabuto', 'Kabutops', 'Aerodactyl', 'Snorlax', 'Articuno', 'Zapdos', 'Moltres', 'Dratini',
    'Dragonair', 'Dragonite', 'Mewtwo', 'Mew', 'Chikorita', 'Bayleef', 'Meganium', 'Cyndaquil', 'Quilava', 'Typhlosion', 'Totodile',
    'Crocnaw', 'Feraligatr', 'Sentret', 'Furret', 'Hoothoot', 'Noctowl', 'Ledyba', 'Ledian', 'Spinarak', 'Ariados', 'Crobat', 'Chinchou',
    'Lanturn', 'Pichu', 'Cleffa', 'Igglybuff', 'Togepi', 'Togetic', 'Natu', 'Xatu', 'Mareep', 'Flaaffy', 'Ampharos', 'Bellossom', 'Marill',
    'Azumarill', 'Sudowoodo', 'Politoed', 'Hoppip', 'Skiploom', 'Jumpluff', 'Aipom', 'Sunkern', 'Sunflora', 'Yanma', 'Wooper', 'Quagsire',
    'Espeon', 'Unbreon', 'Murkrow', 'Slowking', 'Misdreavus', 'Unown', 'Wobbuffet', 'Girafarig', 'Pineco', 'Forretress', 'Dunsparce',
    'Gligar', 'Steelix', 'Snubbull', 'Granbull', 'Qwilfish', 'Scizor', 'Shuckle', 'Heracross', 'Sneasel', 'Teddiursa', 'Ursaring',
    'Slugma', 'Macargo', 'Swinub', 'Poliswine', 'Corsola', 'Remoraid', 'Octillery', 'Delibird', 'Mantine', 'Skarmory', 'Houndour',
    'Houndoom', 'Kingdra', 'Phanpy', 'Donphan', 'Porygon2', 'Stantler', 'Smeargle', 'Tyrogue', 'Hitmontop', 'Smoochum', 'Elekid', 
    'Magby', 'Milktank', 'Blissey', 'Raikou', 'Entei', 'Suicune', 'Larvitar', 'Pupitar', 'Tyranitar', 'Lugia', 'Ho-Oh', 'Celebi',
    'Treeko', 'Grovyle', 'Sceptile', 'Torchic', 'Combusken', 'Blaziken', 'Mudkip', 'Marshtomp', 'Swampert', 'Poochyena', 'Mightyena',
    'Zigzagoon', 'Linoone', 'Wurmple', 'Silicoon', 'Beautifly', 'Cascoon', 'Dustox', 'Lotad', 'Lombre', 'Ludicolo', 'Seedot', 'Nuzleaf',
    'Shiftry', 'Taillow', 'Swellow', 'Wingull', 'Pelipper', 'Ralts', 'Kirlia', 'Gardevoir', 'Surskit', 'Masquerain', 'Shroomish',
    'Breloom', 'Slakoth', 'Vigoroth', 'Slaking', 'Nicada', 'Ninjask', 'Shedinja', 'Whismur', 'Loudred', 'Exploud', 'Majuhita',
    'Haritama', 'Azurill', 'Nozepass', 'Skitty', 'Delcatty', 'Sableye', 'Mawile', 'Aron', 'Larion', 'Aggron', 'Meditite', 'Medicham', 
    'Electrike', 'Manectric', 'Plusle', 'Minum', 'Volbeat', 'Illumise', 'Roselia', 'Gulpin', 'Swalot', 'Carvanha', 'Sharkpedo', 
    'Wailmer', 'Wailord', 'Numel', 'Camerupt', 'Torkoal', 'Spoink', 'Grumpig', 'Spinda', 'Trapinch', 'Vibrava', 'Flygon', 'Cacnea', 
    'Cacturne', 'Swablu', 'Altaria', 'Zangoose', 'Seviper', 'Lunatone', 'Solrock', 'Barboach', 'Whiscash', 'Corphish', 'Crawdaunt', 
    'Baltoy', 'Claydol', 'Lileep', 'Cradily', 'Anorith', 'Armaldo', 'Feebas', 'Milotic', 'Castform', 'Kecleon', 'Shuppet', 'Banette', 
    'Duskull', 'Dusclops', 'Tropius', 'Chimecho', 'Absol', 'Wynaut', 'Snorunt', 'Glalie', 'Spheal', 'Sealeo', 'Walrein', 'Clampearl',
    'Huntail', 'Gorebyss', 'Relicanth', 'Luvdisc', 'Bagon', 'Shelgon', 'Salamence', 'Beldum', 'Metang', 'Metagross', 'Regirock', 
    'Regice', 'Registeel', 'Latias', 'Latios', 'Kyogre', 'Groudon', 'Rayquaza', 'Jirachi', 'Deoxys'
  ];

  let pictures = ['', "Pictures/1.png", "Pictures/2.png", "Pictures/3.png", "Pictures/4.png", "Pictures/5.png", "Pictures/6.png",
    "Pictures/7.png", "Pictures/8.png", "Pictures/9.png", "Pictures/10.png", "Pictures/11.png", "Pictures/12.png", "Pictures/13.png",
    "Pictures/14.png", "Pictures/15.png", "Pictures/16.png", "Pictures/17.png", "Pictures/18.png", "Pictures/19.png",
    "Pictures/20.png", "Pictures/21.png", "Pictures/22.png", "Pictures/23.png", "Pictures/24.png", "Pictures/25.png", "Pictures/26.png",
    "Pictures/27.png", "Pictures/28.png", "Pictures/29.png", "Pictures/30.png", "Pictures/31.png", "Pictures/32.png",
    "Pictures/33.png", "Pictures/34.png", "Pictures/35.png", "Pictures/36.png", "Pictures/37.png", "Pictures/38.png",
    "Pictures/39.png", "Pictures/40.png", "Pictures/41.png", "Pictures/42.png", "Pictures/43.png", "Pictures/44.png",
    "Pictures/45.png", "Pictures/46.png", "Pictures/47.png", "Pictures/48.png", "Pictures/49.png", "Pictures/50.png",
    "Pictures/51.png", "Pictures/52.png", "Pictures/53.png", "Pictures/54.png", "Pictures/55.png", "Pictures/56.png",
    "Pictures/57.png", "Pictures/58.png", "Pictures/59.png", "Pictures/60.png", "Pictures/61.png", "Pictures/62.png", "Pictures/63.png",
    "Pictures/64.png", "Pictures/65.png", "Pictures/66.png", "Pictures/67.png", "Pictures/68.png", "Pictures/69.png",
    "Pictures/70.png", "Pictures/71.png", "Pictures/72.png", "Pictures/73.png", "Pictures/74.png", "Pictures/75.png", "Pictures/76.png",
    "Pictures/77.png", "Pictures/78.png", "Pictures/79.png", "Pictures/80.png", "Pictures/81.png", "Pictures/82.png",
    "Pictures/83.png", "Pictures/84.png", "Pictures/85.png", "Pictures/86.png", "Pictures/87.png", "Pictures/88.png",
    "Pictures/89.png", "Pictures/90.png", "Pictures/91.png", "Pictures/92.png", "Pictures/93.png", "Pictures/94.png",
    "Pictures/95.png", "Pictures/96.png", "Pictures/97.png", "Pictures/98.png", "Pictures/99.png", "Pictures/100.png",
    "Pictures/101.png", "Pictures/102.png", "Pictures/103.png", "Pictures/104.png", "Pictures/105.png", "Pictures/106.png",
    "Pictures/107.png", "Pictures/108.png", "Pictures/109.png", "Pictures/110.png", "Pictures/111.png", "Pictures/112.png", "Pictures/113.png",
    "Pictures/114.png", "Pictures/115.png", "Pictures/116.png", "Pictures/117.png", "Pictures/118.png", "Pictures/119.png",
    "Pictures/120.png", "Pictures/121.png", "Pictures/122.png", "Pictures/123.png", "Pictures/124.png", "Pictures/125.png", "Pictures/126.png",
    "Pictures/127.png", "Pictures/128.png", "Pictures/129.png", "Pictures/130.png", "Pictures/131.png", "Pictures/132.png",
    "Pictures/133.png", "Pictures/134.png", "Pictures/135.png", "Pictures/136.png", "Pictures/137.png", "Pictures/138.png",
    "Pictures/139.png", "Pictures/140.png", "Pictures/141.png", "Pictures/142.png", "Pictures/143.png", "Pictures/144.png",
    "Pictures/145.png", "Pictures/146.png", "Pictures/147.png", "Pictures/148.png", "Pictures/149.png", "Pictures/150.png",
    "Pictures/151.png", "Pictures/152.png", "Pictures/153.png", "Pictures/154.png", "Pictures/155.png", "Pictures/156.png",
    "Pictures/157.png", "Pictures/158.png", "Pictures/159.png", "Pictures/160.png", "Pictures/161.png", "Pictures/162.png", "Pictures/163.png",
    "Pictures/164.png", "Pictures/165.png", "Pictures/166.png", "Pictures/167.png", "Pictures/168.png", "Pictures/169.png",
    "Pictures/170.png", "Pictures/171.png", "Pictures/172.png", "Pictures/173.png", "Pictures/174.png", "Pictures/175.png", "Pictures/176.png",
    "Pictures/177.png", "Pictures/178.png", "Pictures/179.png", "Pictures/180.png", "Pictures/181.png", "Pictures/182.png",
    "Pictures/183.png", "Pictures/184.png", "Pictures/185.png", "Pictures/186.png", "Pictures/187.png", "Pictures/188.png",
    "Pictures/189.png", "Pictures/190.png", "Pictures/191.png", "Pictures/192.png", "Pictures/193.png", "Pictures/194.png",
    "Pictures/195.png", "Pictures/196.png", "Pictures/197.png", "Pictures/198.png", "Pictures/199.png", "Pictures/200.png",
    "Pictures/201.png", "Pictures/202.png", "Pictures/203.png", "Pictures/204.png", "Pictures/205.png", "Pictures/206.png",
    "Pictures/207.png", "Pictures/208.png", "Pictures/209.png", "Pictures/210.png", "Pictures/211.png", "Pictures/212.png", "Pictures/213.png",
    "Pictures/214.png", "Pictures/215.png", "Pictures/216.png", "Pictures/217.png", "Pictures/218.png", "Pictures/219.png",
    "Pictures/220.png", "Pictures/221.png", "Pictures/222.png", "Pictures/223.png", "Pictures/224.png", "Pictures/225.png", "Pictures/226.png",
    "Pictures/227.png", "Pictures/228.png", "Pictures/229.png", "Pictures/230.png", "Pictures/231.png", "Pictures/232.png",
    "Pictures/233.png", "Pictures/234.png", "Pictures/235.png", "Pictures/236.png", "Pictures/237.png", "Pictures/238.png",
    "Pictures/239.png", "Pictures/240.png", "Pictures/241.png", "Pictures/242.png", "Pictures/243.png", "Pictures/244.png",
    "Pictures/245.png", "Pictures/246.png", "Pictures/247.png", "Pictures/248.png", "Pictures/249.png", "Pictures/250.png",
    "Pictures/251.png", "Pictures/252.png", "Pictures/253.png", "Pictures/254.png", "Pictures/255.png", "Pictures/256.png",
    "Pictures/257.png", "Pictures/258.png", "Pictures/259.png", "Pictures/260.png", "Pictures/261.png", "Pictures/262.png", "Pictures/263.png",
    "Pictures/264.png", "Pictures/265.png", "Pictures/266.png", "Pictures/267.png", "Pictures/268.png", "Pictures/269.png",
    "Pictures/270.png", "Pictures/271.png", "Pictures/272.png", "Pictures/273.png", "Pictures/274.png", "Pictures/275.png", "Pictures/276.png",
    "Pictures/277.png", "Pictures/278.png", "Pictures/279.png", "Pictures/280.png", "Pictures/281.png", "Pictures/282.png",
    "Pictures/283.png", "Pictures/284.png", "Pictures/285.png", "Pictures/286.png", "Pictures/287.png", "Pictures/288.png",
    "Pictures/289.png", "Pictures/290.png", "Pictures/291.png", "Pictures/292.png", "Pictures/293.png", "Pictures/294.png",
    "Pictures/295.png", "Pictures/296.png", "Pictures/297.png", "Pictures/298.png", "Pictures/299.png", "Pictures/300.png",
    "Pictures/301.png", "Pictures/302.png", "Pictures/303.png", "Pictures/304.png", "Pictures/305.png", "Pictures/306.png",
    "Pictures/307.png", "Pictures/308.png", "Pictures/309.png", "Pictures/310.png", "Pictures/311.png", "Pictures/312.png", "Pictures/313.png",
    "Pictures/314.png", "Pictures/315.png", "Pictures/316.png", "Pictures/317.png", "Pictures/318.png", "Pictures/319.png",
    "Pictures/320.png", "Pictures/321.png", "Pictures/322.png", "Pictures/323.png", "Pictures/324.png", "Pictures/325.png", "Pictures/326.png",
    "Pictures/327.png", "Pictures/328.png", "Pictures/329.png", "Pictures/330.png", "Pictures/331.png", "Pictures/332.png",
    "Pictures/333.png", "Pictures/334.png", "Pictures/335.png", "Pictures/336.png", "Pictures/337.png", "Pictures/338.png",
    "Pictures/339.png", "Pictures/340.png", "Pictures/341.png", "Pictures/342.png", "Pictures/343.png", "Pictures/344.png",
    "Pictures/345.png", "Pictures/346.png", "Pictures/347.png", "Pictures/348.png", "Pictures/349.png", "Pictures/350.png",
    "Pictures/351.png", "Pictures/352.png", "Pictures/353.png", "Pictures/354.png", "Pictures/355.png", "Pictures/356.png",
    "Pictures/357.png", "Pictures/358.png", "Pictures/359.png", "Pictures/360.png", "Pictures/361.png", "Pictures/362.png", "Pictures/363.png",
    "Pictures/364.png", "Pictures/365.png", "Pictures/366.png", "Pictures/367.png", "Pictures/368.png", "Pictures/369.png",
    "Pictures/370.png", "Pictures/371.png", "Pictures/372.png", "Pictures/373.png", "Pictures/374.png", "Pictures/375.png", "Pictures/376.png",
    "Pictures/377.png", "Pictures/378.png", "Pictures/379.png", "Pictures/380.png", "Pictures/381.png", "Pictures/382.png",
    "Pictures/383.png", "Pictures/384.png", "Pictures/385.png", "Pictures3/86.png"
];
  
  let getName = function(int){
    return name[int];
  }
  let getPicture = function(int){
    return pictures[int];
  }

  return {
    getName,
    getPicture
  };
}());